platform :ios, '17.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      end
    end
  end
end
